// This file is generated by Slice Machine. Update with care!

import Hero from './Hero';
import ImageCards from './ImageCards';
import Text from './Text';

export {
	Hero,
	ImageCards,
	Text,
};

export const components = {
	hero: Hero,
	image_cards: ImageCards,
	text: Text,
};
