// This file is generated by Slice Machine. Update with care!

import Artworks from './Artworks'
import Featured from './Featured'

export {
  Artworks,
  Featured
}

export const components = {
  artworks: Artworks,
  featured: Featured
}
